"""TorqPro AI Gateway - retrieval package.

Faz v3.0.0-alpha.1 (AI Architecture Foundation), per ADR-0017 Karar 3
("Question Bank erişiminin hangi interface üzerinden yapılacağı") and
ADR-0018 (retrieval/grounding strategy, not yet implemented beyond
this foundation).

This module defines the single shared, source-agnostic evidence
contract every retrieval adaptor under ``backend.ai_gateway.retrieval``
returns. It intentionally carries no TorqPro-domain-specific fields
(no calculation IDs, no joint-revision IDs) -- adaptor modules such as
``question_bank_adapter`` populate ``source_type``/``source_id``/
``content_version`` with their own domain's identifiers, but the
*shape* returned to ``context_builder``/``composer``/``evidence_checker``
is uniform across every future source type (library, governance,
docs), matching ADR-0002/ADR-0018's "immutable, dual-language,
citable" evidence design.

Only Question Bank has a concrete adaptor in this foundation phase
(``question_bank_adapter.py``). Additional adaptors (library,
governance/trace, docs) are out of scope for v3.0.0-alpha.1 and are
added in later, separately-approved phases (ADR-0017 Karar 12/13).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class EvidenceSource:
    """One retrievable, citable unit of approved TorqPro content.

    Immutable by construction (frozen dataclass) -- mirrors the
    immutability discipline already used throughout
    ``backend.calculation_engine.request``/``response``.

    Attributes:
        source_type: Domain identifier of the origin adaptor (e.g.
            ``"question_bank"``). Not free text -- each adaptor uses
            exactly one fixed value.
        source_id: The origin domain's own natural key (e.g. a
            Question Bank ``question_id``). Never a synthetic ID
            invented by the AI layer.
        content_version: The origin domain's own immutable content
            version, when the domain has one (Question Bank always
            does, per ADR-0016's ``(question_id, content_version)``
            pairing). ``None`` for source types that are not
            versioned this way.
        title_tr: Short Turkish label for the source, for citation
            display. Never a paraphrase or summary generated by the
            AI layer -- taken verbatim (or truncated verbatim) from
            the origin content.
        title_en: English counterpart of ``title_tr``, same rule.
        body_tr: Turkish body text used for retrieval matching and
            citation. Verbatim origin content.
        body_en: English counterpart of ``body_tr``, same rule.
    """

    source_type: str
    source_id: str
    content_version: Optional[int]
    title_tr: str
    title_en: str
    body_tr: str
    body_en: str


__all__ = ["EvidenceSource"]
